Repository AlvarezR1/team-ogiogi, pull requests merged in 2021-12, with the labels that each got.

#4 se modifico el index
  index.html
Labels: bug

#5 se actualizo el index
  css/style.css
  index.html
Labels: bug

#6 Se arreglo lo que el profe habia comentad
  css/style.css
  img/fondo.jpg
  img/reunion.jpg
  img/test-img.png
  index.html
Labels: bug, documentation

#7 titulo de la segunda parte
  css/style.css
  index.html
Labels: documentation

#8 Smith activity
  css/style.css
  index.html
Labels: bug

#10 se termino la tercera parte
  css/style.css
  img/Hearth.jpg
  img/Joystick.jpg
  img/Oval.jpg
  img/Shape.jpg
  img/Smile.jpg
  img/Timeline.jpg
  img/folder.jpg
  img/phone.jpg
  index.html
Labels: documentation

#9 David branch
  css/style.css
  index.html
Labels: documentation

#11 Smith activity
  css/style.css
  index.html
Labels: bug

#12 Prueba
  css/style.css
  img/Bitmap.jpg
  index.html
Labels: documentation
